name: ðŸ› Bug
description: Report a bug or an incorrect behavior
title: "Write the title here"
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this? (Please read the description)
      description: |
        PLEASE! Make sure to check if this issue is a duplicate. 
        Don't waste our time, we are working hard to make Spotube better for you.

        Try with multiple similar keywords, and check the closed issues too.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: Write what you are experiencing currently.
      placeholder: |
        The app isn't working as expected. It crashes when I do this...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Write what you expected to happen.
      placeholder: |
        The app should do this when I do that...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the issue. A not well written description might lead to the delay in fixing the issue.
      placeholder: |
        1. I opened the app
        2. I did this
        3. And that
        4. Then this happened
  - type: textarea
    attributes:
      label: Logs
      description: |
        If you have any logs, paste them here. Make sure to remove any sensitive information.
        You can find the logs in the app's Settings > Developers > Logs page.
      value: |
        <details>
        <summary>Logs</summary>
        
        ```
        <Replace this line by pasting your logs here>
        ```
        </details>
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: The OS in which you used Spotube to face the issue.
      placeholder: Android, Linux, macOS or Windows? Make sure to include the version too.
    validations:
      required: true
  - type: input
    attributes:
      label: Spotube version
      description: In which version of Spotube did you encounter this bug?
      placeholder: (e.g.) v3.0.0
  - type: dropdown
    attributes:
      label: Installation source
      description: Where did you install Spotube from?
      multiple: true
      options:
        - "Website (spotube.krtirtho.dev)"
        - "GitHub Releases (Binary)"
        - "GitHub Actions (Nightly Binary)"
        - "Play Store (Android)"
        - "F-Droid (Android)"
        - "Arch User Repository (AUR)"
        - "Flathub (Flatpak)"
        - "chocolatey (Windows)"
        - "WinGet (Windows)"
        - "Scoop (Windows)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Anything else you'd like to include?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Self grab
      description: If you are a developer and want to work on this issue yourself, you can check this box and wait for maintainer response. Any contributions are welcome!
      options:
        - label: I'm ready to work on this issue!
          required: false
