.nh
.TH "GH-CONFIG-CLEAR-CACHE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-config-clear-cache - Clear the cli cache


.SH SYNOPSIS
\fBgh config clear-cache [flags]\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Clear the cli cache
$ gh config clear-cache

.EE


.SH SEE ALSO
\fBgh-config(1)\fR
