.nh
.TH "GH-CODESPACE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-codespace - Connect to and manage codespaces


.SH SYNOPSIS
\fBgh codespace [flags]\fR


.SH AVAILABLE COMMANDS
.TP
\fBgh-codespace-code(1)\fR
Open a codespace in Visual Studio Code

.TP
\fBgh-codespace-cp(1)\fR
Copy files between local and remote file systems

.TP
\fBgh-codespace-create(1)\fR
Create a codespace

.TP
\fBgh-codespace-delete(1)\fR
Delete codespaces

.TP
\fBgh-codespace-edit(1)\fR
Edit a codespace

.TP
\fBgh-codespace-jupyter(1)\fR
Open a codespace in JupyterLab

.TP
\fBgh-codespace-list(1)\fR
List codespaces

.TP
\fBgh-codespace-logs(1)\fR
Access codespace logs

.TP
\fBgh-codespace-ports(1)\fR
List ports in a codespace

.TP
\fBgh-codespace-rebuild(1)\fR
Rebuild a codespace

.TP
\fBgh-codespace-ssh(1)\fR
SSH into a codespace

.TP
\fBgh-codespace-stop(1)\fR
Stop a running codespace

.TP
\fBgh-codespace-view(1)\fR
View details about a codespace


.SH ALIASES
gh cs


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
