.nh
.TH "GH-CONFIG-LIST" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-config-list - Print a list of configuration keys and values


.SH SYNOPSIS
\fBgh config list [flags]\fR


.SH OPTIONS
.TP
\fB-h\fR, \fB--host\fR \fB<string>\fR
Get per-host configuration


.SH ALIASES
gh config ls


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-config(1)\fR
