.nh
.TH "GH-EXTENSION-LIST" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-extension-list - List installed extension commands


.SH SYNOPSIS
\fBgh extension list [flags]\fR


.SH ALIASES
gh ext ls, gh extension ls, gh extensions ls


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-extension(1)\fR
