.nh
.TH "GH-EXTENSION-REMOVE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-extension-remove - Remove an installed extension


.SH SYNOPSIS
\fBgh extension remove <name> [flags]\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-extension(1)\fR
