.nh
.TH "GH-GPG-KEY-DELETE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-gpg-key-delete - Delete a GPG key from your GitHub account


.SH SYNOPSIS
\fBgh gpg-key delete <key-id> [flags]\fR


.SH OPTIONS
.TP
\fB-y\fR, \fB--yes\fR
Skip the confirmation prompt


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-gpg-key(1)\fR
