.nh
.TH "GH-GPG-KEY" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-gpg-key - Manage GPG keys


.SH SYNOPSIS
\fBgh gpg-key <command> [flags]\fR


.SH DESCRIPTION
Manage GPG keys registered with your GitHub account.


.SH AVAILABLE COMMANDS
.TP
\fBgh-gpg-key-add(1)\fR
Add a GPG key to your GitHub account

.TP
\fBgh-gpg-key-delete(1)\fR
Delete a GPG key from your GitHub account

.TP
\fBgh-gpg-key-list(1)\fR
Lists GPG keys in your GitHub account


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
