.nh
.TH "GH-ISSUE-LIST" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-issue-list - List issues in a repository


.SH SYNOPSIS
\fBgh issue list [flags]\fR


.SH DESCRIPTION
List issues in a GitHub repository. By default, this only lists open issues.

.PP
The search query syntax is documented here:

\[la]https://docs.github.com/en/search\-github/searching\-on\-github/searching\-issues\-and\-pull\-requests\[ra]


.SH OPTIONS
.TP
\fB--app\fR \fB<string>\fR
Filter by GitHub App author

.TP
\fB-a\fR, \fB--assignee\fR \fB<string>\fR
Filter by assignee

.TP
\fB-A\fR, \fB--author\fR \fB<string>\fR
Filter by author

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--json\fR \fB<fields>\fR
Output JSON with the specified fields

.TP
\fB-l\fR, \fB--label\fR \fB<strings>\fR
Filter by label

.TP
\fB-L\fR, \fB--limit\fR \fB<int> (default 30)\fR
Maximum number of issues to fetch

.TP
\fB--mention\fR \fB<string>\fR
Filter by mention

.TP
\fB-m\fR, \fB--milestone\fR \fB<string>\fR
Filter by milestone number or title

.TP
\fB-S\fR, \fB--search\fR \fB<query>\fR
Search issues with query

.TP
\fB-s\fR, \fB--state\fR \fB<string> (default "open")\fR
Filter by state: {open|closed|all}

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB-w\fR, \fB--web\fR
List issues in the web browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH ALIASES
gh issue ls


.SH JSON FIELDS
\fBassignees\fR, \fBauthor\fR, \fBbody\fR, \fBclosed\fR, \fBclosedAt\fR, \fBclosedByPullRequestsReferences\fR, \fBcomments\fR, \fBcreatedAt\fR, \fBid\fR, \fBisPinned\fR, \fBlabels\fR, \fBmilestone\fR, \fBnumber\fR, \fBprojectCards\fR, \fBprojectItems\fR, \fBreactionGroups\fR, \fBstate\fR, \fBstateReason\fR, \fBtitle\fR, \fBupdatedAt\fR, \fBurl\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
$ gh issue list --label "bug" --label "help wanted"
$ gh issue list --author monalisa
$ gh issue list --assignee "@me"
$ gh issue list --milestone "The big 1.0"
$ gh issue list --search "error no:assignee sort:created-asc"
$ gh issue list --state all

.EE


.SH SEE ALSO
\fBgh-issue(1)\fR
