.nh
.TH "GH-LABEL-DELETE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-label-delete - Delete a label from a repository


.SH SYNOPSIS
\fBgh label delete <name> [flags]\fR


.SH OPTIONS
.TP
\fB--yes\fR
Confirm deletion without prompting


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-label(1)\fR
