.nh
.TH "GH-LABEL-EDIT" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-label-edit - Edit a label


.SH SYNOPSIS
\fBgh label edit <name> [flags]\fR


.SH DESCRIPTION
Update a label on GitHub.

.PP
A label can be renamed using the \fB--name\fR flag.

.PP
The label color needs to be 6 character hex value.


.SH OPTIONS
.TP
\fB-c\fR, \fB--color\fR \fB<string>\fR
Color of the label

.TP
\fB-d\fR, \fB--description\fR \fB<string>\fR
Description of the label

.TP
\fB-n\fR, \fB--name\fR \fB<string>\fR
New name of the label


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Update the color of the bug label
$ gh label edit bug --color FF0000

# Rename and edit the description of the bug label
$ gh label edit bug --name big-bug --description "Bigger than normal bug"

.EE


.SH SEE ALSO
\fBgh-label(1)\fR
