.nh
.TH "GH-ORG" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-org - Manage organizations


.SH SYNOPSIS
\fBgh org <command> [flags]\fR


.SH DESCRIPTION
Work with GitHub organizations.


.SH GENERAL COMMANDS
.TP
\fBgh-org-list(1)\fR
List organizations for the authenticated user.


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
$ gh org list

.EE


.SH SEE ALSO
\fBgh(1)\fR
