.nh
.TH "GH-PR-READY" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-pr-ready - Mark a pull request as ready for review


.SH SYNOPSIS
\fBgh pr ready [<number> | <url> | <branch>] [flags]\fR


.SH DESCRIPTION
Mark a pull request as ready for review.

.PP
Without an argument, the pull request that belongs to the current branch
is marked as ready.

.PP
If supported by your plan, convert to draft with \fB--undo\fR


.SH OPTIONS
.TP
\fB--undo\fR
Convert a pull request to "draft"


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-pr(1)\fR
