.nh
.TH "GH-PROJECT-CLOSE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-project-close - Close a project


.SH SYNOPSIS
\fBgh project close [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB--undo\fR
Reopen a closed project


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Close project "1" owned by monalisa
$ gh project close 1 --owner monalisa

# Reopen closed project "1" owned by github
$ gh project close 1 --owner github --undo

.EE


.SH SEE ALSO
\fBgh-project(1)\fR
