.nh
.TH "GH-REPO-DELETE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-repo-delete - Delete a repository


.SH SYNOPSIS
\fBgh repo delete [<repository>] [flags]\fR


.SH DESCRIPTION
Delete a GitHub repository.

.PP
With no argument, deletes the current repository. Otherwise, deletes the specified repository.

.PP
Deletion requires authorization with the \fBdelete_repo\fR scope.
To authorize, run \fBgh auth refresh -s delete_repo\fR


.SH OPTIONS
.TP
\fB--yes\fR
Confirm deletion without prompting


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-repo(1)\fR
