.nh
.TH "GH-REPO-RENAME" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-repo-rename - Rename a repository


.SH SYNOPSIS
\fBgh repo rename [<new-name>] [flags]\fR


.SH DESCRIPTION
Rename a GitHub repository.

.PP
\fB<new-name>\fR is the desired repository name without the owner.

.PP
By default, the current repository is renamed. Otherwise, the repository specified
with \fB--repo\fR is renamed.

.PP
To transfer repository ownership to another user account or organization,
you must follow additional steps on \fBgithub.com\fR\&.

.PP
For more information on transferring repository ownership, see:

\[la]https://docs.github.com/en/repositories/creating\-and\-managing\-repositories/transferring\-a\-repository\[ra]


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format

.TP
\fB-y\fR, \fB--yes\fR
Skip the confirmation prompt


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Rename the current repository (foo/bar -> foo/baz)
$ gh repo rename baz

# Rename the specified repository (qux/quux -> qux/baz)
$ gh repo rename -R qux/quux baz

.EE


.SH SEE ALSO
\fBgh-repo(1)\fR
