.nh
.TH "GH-REPO-LICENSE-LIST" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-repo-license-list - List common repository licenses


.SH SYNOPSIS
\fBgh repo license list [flags]\fR


.SH DESCRIPTION
List common repository licenses.

.PP
For even more licenses, visit 
\[la]https://choosealicense.com/appendix\[ra]


.SH ALIASES
gh repo license ls


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-repo-license(1)\fR
