.nh
.TH "GH-REPO-GITIGNORE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-repo-gitignore - List and view available repository gitignore templates


.SH SYNOPSIS
\fBgh repo gitignore <command> [flags]\fR


.SH AVAILABLE COMMANDS
.TP
\fBgh-repo-gitignore-list(1)\fR
List available repository gitignore templates

.TP
\fBgh-repo-gitignore-view(1)\fR
View an available repository gitignore template


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-repo(1)\fR
