.nh
.TH "GH-RELEASE-VIEW" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-release-view - View information about a release


.SH SYNOPSIS
\fBgh release view [<tag>] [flags]\fR


.SH DESCRIPTION
View information about a GitHub Release.

.PP
Without an explicit tag name argument, the latest release in the project
is shown.


.SH OPTIONS
.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--json\fR \fB<fields>\fR
Output JSON with the specified fields

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB-w\fR, \fB--web\fR
Open the release in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH JSON FIELDS
\fBapiUrl\fR, \fBassets\fR, \fBauthor\fR, \fBbody\fR, \fBcreatedAt\fR, \fBdatabaseId\fR, \fBid\fR, \fBisDraft\fR, \fBisImmutable\fR, \fBisPrerelease\fR, \fBname\fR, \fBpublishedAt\fR, \fBtagName\fR, \fBtarballUrl\fR, \fBtargetCommitish\fR, \fBuploadUrl\fR, \fBurl\fR, \fBzipballUrl\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-release(1)\fR
