.nh
.TH "GH-REPO-LICENSE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-repo-license - Explore repository licenses


.SH SYNOPSIS
\fBgh repo license <command> [flags]\fR


.SH AVAILABLE COMMANDS
.TP
\fBgh-repo-license-list(1)\fR
List common repository licenses

.TP
\fBgh-repo-license-view(1)\fR
View a specific repository license


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-repo(1)\fR
