.nh
.TH "GH-RUN-DELETE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-run-delete - Delete a workflow run


.SH SYNOPSIS
\fBgh run delete [<run-id>] [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Interactively select a run to delete
$ gh run delete

# Delete a specific run
$ gh run delete 12345

.EE


.SH SEE ALSO
\fBgh-run(1)\fR
