.nh
.TH "GH-SECRET-DELETE" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-secret-delete - Delete secrets


.SH SYNOPSIS
\fBgh secret delete <secret-name> [flags]\fR


.SH DESCRIPTION
Delete a secret on one of the following levels:
- repository (default): available to GitHub Actions runs or Dependabot in a repository
- environment: available to GitHub Actions runs for a deployment environment in a repository
- organization: available to GitHub Actions runs, Dependabot, or Codespaces within an organization
- user: available to Codespaces for your user


.SH OPTIONS
.TP
\fB-a\fR, \fB--app\fR \fB<string>\fR
Delete a secret for a specific application: {actions|codespaces|dependabot}

.TP
\fB-e\fR, \fB--env\fR \fB<string>\fR
Delete a secret for an environment

.TP
\fB-o\fR, \fB--org\fR \fB<string>\fR
Delete a secret for an organization

.TP
\fB-u\fR, \fB--user\fR
Delete a secret for your user


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH ALIASES
gh secret remove


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-secret(1)\fR
