.nh
.TH "GH-SECRET-LIST" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-secret-list - List secrets


.SH SYNOPSIS
\fBgh secret list [flags]\fR


.SH DESCRIPTION
List secrets on one of the following levels:
- repository (default): available to GitHub Actions runs or Dependabot in a repository
- environment: available to GitHub Actions runs for a deployment environment in a repository
- organization: available to GitHub Actions runs, Dependabot, or Codespaces within an organization
- user: available to Codespaces for your user


.SH OPTIONS
.TP
\fB-a\fR, \fB--app\fR \fB<string>\fR
List secrets for a specific application: {actions|codespaces|dependabot}

.TP
\fB-e\fR, \fB--env\fR \fB<string>\fR
List secrets for an environment

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--json\fR \fB<fields>\fR
Output JSON with the specified fields

.TP
\fB-o\fR, \fB--org\fR \fB<string>\fR
List secrets for an organization

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB-u\fR, \fB--user\fR
List a secret for your user


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH ALIASES
gh secret ls


.SH JSON FIELDS
\fBname\fR, \fBnumSelectedRepos\fR, \fBselectedReposURL\fR, \fBupdatedAt\fR, \fBvisibility\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-secret(1)\fR
