.nh
.TH "GH-SEARCH" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-search - Search for repositories, issues, and pull requests


.SH SYNOPSIS
\fBgh search <command> [flags]\fR


.SH DESCRIPTION
Search across all of GitHub.


.SH AVAILABLE COMMANDS
.TP
\fBgh-search-code(1)\fR
Search within code

.TP
\fBgh-search-commits(1)\fR
Search for commits

.TP
\fBgh-search-issues(1)\fR
Search for issues

.TP
\fBgh-search-prs(1)\fR
Search for pull requests

.TP
\fBgh-search-repos(1)\fR
Search for repositories


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
