.nh
.TH "GH-SSH-KEY" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-ssh-key - Manage SSH keys


.SH SYNOPSIS
\fBgh ssh-key <command> [flags]\fR


.SH DESCRIPTION
Manage SSH keys registered with your GitHub account.


.SH AVAILABLE COMMANDS
.TP
\fBgh-ssh-key-add(1)\fR
Add an SSH key to your GitHub account

.TP
\fBgh-ssh-key-delete(1)\fR
Delete an SSH key from your GitHub account

.TP
\fBgh-ssh-key-list(1)\fR
Lists SSH keys in your GitHub account


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
