.nh
.TH "GH-WORKFLOW" "1" "Jul 2025" "GitHub CLI 2.76.2" "GitHub CLI manual"

.SH NAME
gh-workflow - View details about GitHub Actions workflows


.SH SYNOPSIS
\fBgh workflow <command> [flags]\fR


.SH DESCRIPTION
List, view, and run workflows in GitHub Actions.


.SH AVAILABLE COMMANDS
.TP
\fBgh-workflow-disable(1)\fR
Disable a workflow

.TP
\fBgh-workflow-enable(1)\fR
Enable a workflow

.TP
\fBgh-workflow-list(1)\fR
List workflows

.TP
\fBgh-workflow-run(1)\fR
Run a workflow by creating a workflow_dispatch event

.TP
\fBgh-workflow-view(1)\fR
View the summary of a workflow


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
