/*
 * Copyright (C) 2026 Kingkor Roy Tirtho and Spotube Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package dev.krtirtho.spotube.core.jam

import co.touchlab.kermit.Logger
import dev.krtirtho.spotube.core.audioplayer.AudioPlayerInterface
import dev.krtirtho.spotube.core.di.injectLogger
import dev.krtirtho.spotube.modules.settings.SettingsProvider
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import org.koin.core.component.KoinComponent
import uniffi.compose_app.IceServerConfig
import uniffi.compose_app.WebrtcEventHandler
import uniffi.compose_app.WebrtcPeerConnection
import uniffi.compose_app.createWebrtcPeerConnection

/**
 * An invite generated by the host for one guest slot. The [sdp] offer is shared
 * via a deep link; once the guest's answer comes back, [JamSessionService.acceptAnswer]
 * completes the handshake for that slot.
 */
data class JamInvite(
    val id: String,
    val sdp: String,
)

class JamSessionService(
    private val audioPlayer: AudioPlayerInterface,
    private val settingsProvider: SettingsProvider,
) : KoinComponent {
    val logger by injectLogger<JamSessionService>()
    private val log = Logger.withTag("JamSessionService")

    private val json = Json {
        ignoreUnknownKeys = true
        classDiscriminator = "type"
        encodeDefaults = true
    }

    private val _role = MutableStateFlow<JamRole?>(null)
    val role: StateFlow<JamRole?> = _role.asStateFlow()

    private val _participants = MutableStateFlow<List<JamParticipant>>(emptyList())
    val participants: StateFlow<List<JamParticipant>> = _participants.asStateFlow()

    private val _isActive = MutableStateFlow(false)
    val isActive: StateFlow<Boolean> = _isActive.asStateFlow()

    private val _localParticipantId = MutableStateFlow<String?>(null)
    val localParticipantId: StateFlow<String?> = _localParticipantId.asStateFlow()

    private val _incomingMessages = MutableSharedFlow<JamMessage>(extraBufferCapacity = 64)
    val incomingMessages = _incomingMessages.asSharedFlow()

    private val _incomingSuggestions = MutableSharedFlow<JamMessage>(extraBufferCapacity = 32)
    val incomingSuggestions = _incomingSuggestions.asSharedFlow()

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    /** Host side: invites whose answers have not arrived yet. */
    private val pendingInvites = mutableMapOf<String, WebrtcPeerConnection>()

    /** Host side: guests whose handshake completed. Keyed by invite id. */
    private val connectedGuests = mutableMapOf<String, WebrtcPeerConnection>()

    /** Guest side: the single connection to the host. */
    private var hostConnection: WebrtcPeerConnection? = null

    suspend fun createSession(): String {
        log.i { "Creating jam session" }
        val hostName = resolveParticipantName(defaultPrefix = "Host")

        _role.value = JamRole.Host
        _localParticipantId.value = "host"
        _participants.value = listOf(
            JamParticipant(
                id = "host",
                displayName = hostName,
                isHost = true,
            )
        )
        _isActive.value = true

        return generateInvite().sdp
    }

    /**
     * Generates a new invite (peer connection + SDP offer with bundled ICE candidates).
     * Each invite admits exactly one guest.
     */
    suspend fun generateInvite(): JamInvite {
        if (_role.value != JamRole.Host) {
            error("generateInvite can only be called by the host")
        }
        val inviteId = "guest-${randomShortId()}"
        log.i { "Generating invite $inviteId" }

        val pc = createWebrtcPeerConnection(
            iceServers = defaultIceServers(),
            handler = guestEventHandler(inviteId),
        )

        pc.createDataChannel(CHANNEL_LABEL)
        val offer = pc.createOffer()
        pendingInvites[inviteId] = pc
        return JamInvite(id = inviteId, sdp = offer)
    }

    /**
     * Completes a guest's handshake: applies their SDP answer to the peer connection
     * created for [inviteId] and adds them to the participant list.
     *
     * When [inviteId] is null, the oldest still-pending invite is used — convenient
     * when an answer deep link arrives out of band.
     *
     * @param answerSdp raw SDP answer body (not a deep link).
     * @param peerName display name of the guest, taken from their answer link if available.
     */
    suspend fun acceptAnswer(inviteId: String?, answerSdp: String, peerName: String): Boolean {
        if (_role.value != JamRole.Host) {
            log.w { "acceptAnswer ignored: not hosting" }
            return false
        }
        val resolvedId = inviteId ?: pendingInvites.keys.firstOrNull()
        if (resolvedId == null) {
            log.w { "acceptAnswer: no pending invite" }
            return false
        }
        val pc = pendingInvites.remove(resolvedId)
        if (pc == null) {
            log.w { "acceptAnswer: no pending invite '$resolvedId'" }
            return false
        }
        runCatching { pc.setRemoteAnswer(answerSdp) }
            .onFailure { e ->
                log.w(e) { "Failed to apply answer for $inviteId" }
                scope.launch { runCatching { pc.shutdown() } }
                return false
            }
        connectedGuests[resolvedId] = pc
        _participants.update { current ->
            current + JamParticipant(
                id = resolvedId,
                displayName = peerName.ifBlank { "Guest-${resolvedId.takeLast(4)}" },
                isHost = false,
            )
        }
        log.i { "Guest $resolvedId ($peerName) joined" }
        return true
    }

    suspend fun joinSession(offerSdp: String): String {
        log.i { "Joining jam session" }
        val participantName = resolveParticipantName(defaultPrefix = "Guest")

        val pc = createWebrtcPeerConnection(
            iceServers = defaultIceServers(),
            handler = eventHandler,
        )

        hostConnection = pc
        _role.value = JamRole.Guest
        _localParticipantId.value = "guest"
        _isActive.value = true

        // The data channel arrives in-band from the host's offer via on_data_channel;
        // we only answer here.
        pc.setRemoteOffer(offerSdp)
        val answer = pc.createAnswer()
        log.i { "Generated SDP answer (length=${answer.length})" }
        return answer
    }

    suspend fun sendMessage(message: JamMessage, guestId: String? = null) {
        val payload = json.encodeToString(JamMessage.serializer(), message)
        when (_role.value) {
            JamRole.Host -> {
                val targets = if (guestId != null) {
                    listOfNotNull(connectedGuests[guestId])
                } else {
                    connectedGuests.values.toList()
                }
                targets.forEach { pc ->
                    runCatching { pc.sendData(CHANNEL_LABEL, payload) }
                        .onFailure { e -> log.w(e) { "Failed to send to guest" } }
                }
            }

            JamRole.Guest -> {
                hostConnection?.sendData(CHANNEL_LABEL, payload)
            }

            null -> log.w { "sendMessage called while no session is active" }
        }
    }

    suspend fun leave() {
        log.i { "Leaving jam session" }
        runCatching { sendMessage(JamMessage.Leave()) }
        shutdownAll()
        _role.value = null
        _participants.value = emptyList()
        _isActive.value = false
        _localParticipantId.value = null
    }

    suspend fun broadcastPlaybackCommand(command: PlaybackCmd) {
        if (_role.value != JamRole.Host) return
        sendMessage(JamMessage.PlaybackCommand(command))
    }

    suspend fun broadcastQueueState(
        items: List<JamMediaItem>,
        currentIndex: Int,
        isPlaying: Boolean,
        positionMs: Long,
    ) {
        if (_role.value != JamRole.Host) return
        sendMessage(JamMessage.QueueState(items, currentIndex, isPlaying, positionMs))
    }

    suspend fun suggestTrack(mediaItem: JamMediaItem) {
        if (_role.value != JamRole.Guest) return
        sendMessage(JamMessage.SuggestTrack(mediaItem))
    }

    suspend fun suggestPlaylist(tracks: List<JamMediaItem>) {
        if (_role.value != JamRole.Guest) return
        sendMessage(JamMessage.SuggestPlaylist(tracks))
    }

    /**
     * ICE servers for global peer-to-peer jam sessions: multiple STUN servers for
     * NAT traversal plus a TURN relay for symmetric NATs and strict firewalls.
     * Unreachable servers no longer stall offer/answer creation — the webrtc
     * driver completes gathering once every STUN client has answered or timed out,
     * and [WebrtcPeerConnection] bounds the wait anyway.
     */
    private fun defaultIceServers(): List<IceServerConfig> = listOf(
        IceServerConfig(
            urls = listOf(
                "stun:stun.cloudflare.com:3478",
                "stun:stun1.l.google.com:19302",
                "stun:stun.l.google.com:19302",
            ),
            username = "",
            credential = "",
        ),
        IceServerConfig(
            urls = listOf("turn:openrelay.metered.ca:80"),
            username = "openrelayproject",
            credential = "openrelayproject",
        ),
    )

    private suspend fun resolveParticipantName(defaultPrefix: String): String {
        val settings = settingsProvider.settingsState.first()
        return settings?.jamParticipantName?.ifBlank { "$defaultPrefix-${randomShortId()}" }
            ?: "$defaultPrefix-${randomShortId()}"
    }

    /**
     * Per-guest handler so messages received on a guest's connection can be
     * attributed back to that guest (needed for kick-on-leave and targeted sends).
     */
    private fun guestEventHandler(guestId: String) = object : WebrtcEventHandler {
        override fun onIceCandidate(candidate: String) {
            log.i { "[$guestId] ICE candidate: $candidate" }
        }

        override fun onIceGatheringStateChange(state: String) {
            log.i { "[$guestId] ICE gathering state: $state" }
        }

        override fun onConnectionStateChange(state: String) {
            log.i { "[$guestId] Connection state: $state" }
        }

        override fun onDataChannelOpen(label: String) {
            log.i { "[$guestId] Data channel '$label' open" }
        }

        override fun onDataChannelMessage(label: String, data: String) {
            handleIncomingMessage(data, fromGuestId = guestId)
        }

        override fun onDataChannelClose(label: String) {
            log.i { "[$guestId] Data channel closed" }
        }
    }

    private val eventHandler = object : WebrtcEventHandler {
        override fun onIceCandidate(candidate: String) {
            log.i { "ICE candidate: $candidate" }
        }

        override fun onIceGatheringStateChange(state: String) {
            log.i { "ICE gathering state: $state" }
        }

        override fun onConnectionStateChange(state: String) {
            log.i { "Connection state: $state" }
        }

        override fun onDataChannelOpen(label: String) {
            log.i { "Data channel '$label' open" }
        }

        override fun onDataChannelMessage(label: String, data: String) {
            handleIncomingMessage(data, fromGuestId = null)
        }

        override fun onDataChannelClose(label: String) {
            log.i { "Data channel closed" }
        }
    }

    private fun handleIncomingMessage(data: String, fromGuestId: String?) {
        try {
            val message = json.decodeFromString(JamMessage.serializer(), data)
            _incomingMessages.tryEmit(message)
            when (message) {
                is JamMessage.SuggestTrack, is JamMessage.SuggestPlaylist -> {
                    _incomingSuggestions.tryEmit(message)
                }

                is JamMessage.Leave -> {
                    if (_role.value == JamRole.Host && fromGuestId != null) {
                        val leavingPc = connectedGuests.remove(fromGuestId)
                        scope.launch {
                            runCatching { leavingPc?.shutdown() }
                        }
                        _participants.update { current ->
                            current.filterNot { it.id == fromGuestId }
                        }
                    } else if (_role.value == JamRole.Guest) {
                        scope.launch { leave() }
                    }
                }

                else -> Unit
            }
        } catch (e: Exception) {
            log.w(e) { "Failed to parse jam message" }
        }
    }

    private suspend fun shutdownAll() {
        pendingInvites.values.forEach { runCatching { it.shutdown() } }
        connectedGuests.values.forEach { runCatching { it.shutdown() } }
        runCatching { hostConnection?.shutdown() }
        pendingInvites.clear()
        connectedGuests.clear()
        hostConnection = null
    }
}

private const val CHANNEL_LABEL = "jam"

private fun <T> MutableStateFlow<T>.update(transform: (T) -> T) {
    value = transform(value)
}

private fun randomShortId(): String {
    val chars = "0123456789abcdef"
    return buildString(8) {
        repeat(8) {
            append(chars[kotlin.random.Random.nextInt(chars.length)])
        }
    }
}