/*
 * Copyright (C) 2026 Kingkor Roy Tirtho and Spotube Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package dev.krtirtho.spotube.core.jam

import co.touchlab.kermit.Logger
import dev.krtirtho.spotube.core.audioplayer.AudioPlayerInterface
import dev.krtirtho.spotube.core.audioplayer.AudioPlayerQueue
import dev.krtirtho.spotube.core.di.injectLogger
import dev.krtirtho.spotube.modules.settings.SettingsProvider
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import org.koin.core.component.KoinComponent
import uniffi.compose_app.IceServerConfig
import uniffi.compose_app.WebrtcEventHandler
import uniffi.compose_app.WebrtcPeerConnection
import uniffi.compose_app.createWebrtcPeerConnection

/**
 * An invite generated by the host for one guest slot. The [sdp] offer is shared
 * via a deep link; once the guest's answer comes back, [JamSessionService.acceptAnswer]
 * completes the handshake for that slot.
 */
data class JamInvite(
    val id: String,
    val sdp: String,
)

/**
 * Owns the peer connections of a jam session (star topology: host relays state
 * to all guests) and the hello/welcome handshake, participant bookkeeping and
 * kick/ban. Playback & queue synchronization itself is delegated to
 * [QueueSyncManager], which runs while a session is active.
 */
class JamSessionService(
    private val audioPlayer: AudioPlayerInterface,
    private val audioPlayerQueue: AudioPlayerQueue,
    private val settingsProvider: SettingsProvider,
) : KoinComponent {
    val logger by injectLogger<JamSessionService>()
    private val log = Logger.withTag("JamSessionService")

    /**
     * Playback/queue synchronization. Owned by this service (not a Koin bean) so
     * the two don't form a circular dependency; it's started/stopped with the
     * session lifecycle.
     */
    private val queueSyncManager = QueueSyncManager(
        audioPlayer = audioPlayer,
        audioPlayerQueue = audioPlayerQueue,
        jamSession = this,
    )

    private val json = Json {
        ignoreUnknownKeys = true
        classDiscriminator = "type"
        encodeDefaults = true
    }

    private val _role = MutableStateFlow<JamRole?>(null)
    val role: StateFlow<JamRole?> = _role.asStateFlow()

    private val _participants = MutableStateFlow<List<JamParticipant>>(emptyList())
    val participants: StateFlow<List<JamParticipant>> = _participants.asStateFlow()

    private val _isActive = MutableStateFlow(false)
    val isActive: StateFlow<Boolean> = _isActive.asStateFlow()

    private val _localParticipantId = MutableStateFlow<String?>(null)
    val localParticipantId: StateFlow<String?> = _localParticipantId.asStateFlow()

    private val _isConnected = MutableStateFlow(false)
    val isConnected: StateFlow<Boolean> = _isConnected.asStateFlow()

    private val _incomingMessages = MutableSharedFlow<JamMessage>(extraBufferCapacity = 64)
    val incomingMessages = _incomingMessages.asSharedFlow()

    private val _incomingSuggestions = MutableSharedFlow<JamMessage>(extraBufferCapacity = 32)
    val incomingSuggestions = _incomingSuggestions.asSharedFlow()

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    /** Host side: invites whose answers have not arrived yet. */
    private val pendingInvites = mutableMapOf<String, WebrtcPeerConnection>()

    /** Host side: guests whose handshake completed. Keyed by invite id. */
    private val connectedGuests = mutableMapOf<String, WebrtcPeerConnection>()

    /** Host side: guest device ids, used for bans. */
    private val guestDeviceIds = mutableMapOf<String, String>()

    /** Host side: latest RTCPeerConnection state per guest ("connecting", "connected", "failed"...). */
    private val guestConnectionStates = mutableMapOf<String, String>()

    /** Host side: device ids banned for this session. */
    private val bannedDeviceIds = mutableSetOf<String>()

    /** Guest side: the single connection to the host. */
    private var hostConnection: WebrtcPeerConnection? = null

    private var hostDisplayName: String = "Host"
    private var guestDisplayName: String = "Guest"

    suspend fun createSession(): String {
        log.i { "Creating jam session" }
        hostDisplayName = resolveParticipantName(defaultPrefix = "Host")

        _role.value = JamRole.Host
        _localParticipantId.value = "host"
        _participants.value = listOf(
            JamParticipant(
                id = "host",
                displayName = hostDisplayName,
                isHost = true,
            )
        )
        _isActive.value = true
        queueSyncManager.start()

        return generateInvite().sdp
    }

    /**
     * Generates a new invite (peer connection + SDP offer with bundled ICE candidates).
     * Each invite admits exactly one guest.
     */
    suspend fun generateInvite(): JamInvite {
        if (_role.value != JamRole.Host) {
            error("generateInvite can only be called by the host")
        }
        val inviteId = "guest-${randomShortId()}"
        log.i { "Generating invite $inviteId" }

        val pc = createWebrtcPeerConnection(
            iceServers = defaultIceServers(),
            handler = guestEventHandler(inviteId),
        )

        pc.createDataChannel(CHANNEL_LABEL)
        val offer = pc.createOffer()
        pendingInvites[inviteId] = pc
        return JamInvite(id = inviteId, sdp = offer)
    }

    /**
     * Completes a guest's handshake: applies their SDP answer to the peer connection
     * created for [inviteId] and adds them to the participant list.
     *
     * When [inviteId] is null, the oldest still-pending invite is used — convenient
     * when an answer deep link arrives out of band.
     *
     * @param answerSdp raw SDP answer body (not a deep link).
     * @param peerName display name of the guest, taken from their answer link if available.
     */
    suspend fun acceptAnswer(inviteId: String?, answerSdp: String, peerName: String): Boolean {
        if (_role.value != JamRole.Host) {
            log.w { "acceptAnswer ignored: not hosting" }
            return false
        }
        val resolvedId = inviteId ?: pendingInvites.keys.firstOrNull()
        if (resolvedId == null) {
            log.w { "acceptAnswer: no pending invite" }
            return false
        }
        val pc = pendingInvites.remove(resolvedId)
        if (pc == null) {
            log.w { "acceptAnswer: no pending invite '$resolvedId'" }
            return false
        }
        runCatching { pc.setRemoteAnswer(answerSdp) }
            .onFailure { e ->
                log.w(e) { "Failed to apply answer for $inviteId" }
                scope.launch { runCatching { pc.shutdown() } }
                return false
            }
        connectedGuests[resolvedId] = pc
        _participants.update { current ->
            current + JamParticipant(
                id = resolvedId,
                displayName = peerName.ifBlank { "Guest-${resolvedId.takeLast(4)}" },
                isHost = false,
            )
        }
        log.i { "Guest $resolvedId ($peerName) joined" }
        broadcastParticipantList()
        return true
    }

    suspend fun joinSession(offerSdp: String, hostName: String? = null): String {
        log.i { "Joining jam session" }
        guestDisplayName = resolveParticipantName(defaultPrefix = "Guest")

        val pc = createWebrtcPeerConnection(
            iceServers = defaultIceServers(),
            handler = eventHandler,
        )

        hostConnection = pc
        _role.value = JamRole.Guest
        _localParticipantId.value = null
        _participants.value = listOf(
            JamParticipant(
                id = "host",
                displayName = hostName?.ifBlank { null } ?: "Host",
                isHost = true,
            )
        )
        _isActive.value = true
        queueSyncManager.start()

        // The data channel arrives in-band from the host's offer via on_data_channel;
        // we only answer here.
        pc.setRemoteOffer(offerSdp)
        val answer = pc.createAnswer()
        log.i { "Generated SDP answer (length=${answer.length})" }
        return answer
    }

    suspend fun sendMessage(message: JamMessage, guestId: String? = null) {
        val payload = json.encodeToString(JamMessage.serializer(), message)
        when (_role.value) {
            JamRole.Host -> {
                if (guestId != null) {
                    val pc = connectedGuests[guestId] ?: return
                    runCatching { pc.sendData(CHANNEL_LABEL, payload) }
                        .onFailure { e ->
                            log.w(e) { "Failed to send to guest $guestId" }
                            onSendFailure(guestId)
                        }
                } else {
                    val dead = mutableListOf<String>()
                    connectedGuests.forEach { (id, pc) ->
                        runCatching { pc.sendData(CHANNEL_LABEL, payload) }
                            .onFailure { e ->
                                log.w(e) { "Failed to send to guest $id" }
                                dead += id
                            }
                    }
                    dead.forEach { id -> onSendFailure(id) }
                }
            }

            JamRole.Guest -> {
                runCatching { hostConnection?.sendData(CHANNEL_LABEL, payload) }
                    .onFailure { e ->
                        log.w(e) { "Failed to send to host" }
                    }
            }

            null -> log.w { "sendMessage called while no session is active" }
        }
    }

    /**
     * A send to a guest failed. If that guest's connection has already given up
     * (failed/closed), drop them from the session; while the connection is merely
     * "connecting" the channel may simply not be open yet, so keep them.
     */
    private fun onSendFailure(guestId: String) {
        val state = guestConnectionStates[guestId]
        if (state == "failed" || state == "closed" || state == "disconnected") {
            scope.launch { removeGuest(guestId) }
        }
    }

    suspend fun leave() {
        log.i { "Leaving jam session" }
        queueSyncManager.stop()
        runCatching { sendMessage(JamMessage.Leave()) }
        shutdownAll()
        _role.value = null
        _participants.value = emptyList()
        _isActive.value = false
        _isConnected.value = false
        _localParticipantId.value = null
        guestDeviceIds.clear()
        guestConnectionStates.clear()
        bannedDeviceIds.clear()
    }

    suspend fun broadcastPlaybackCommand(command: PlaybackCmd) {
        if (_role.value != JamRole.Host) return
        sendMessage(JamMessage.PlaybackCommand(command))
    }

    suspend fun broadcastQueueState(
        items: List<JamMediaItem>,
        currentIndex: Int,
        isPlaying: Boolean,
        positionMs: Long,
    ) {
        if (_role.value != JamRole.Host) return
        sendMessage(JamMessage.QueueState(items, currentIndex, isPlaying, positionMs))
    }

    suspend fun suggestTrack(mediaItem: JamMediaItem) {
        if (_role.value != JamRole.Guest) return
        sendMessage(JamMessage.SuggestTrack(mediaItem))
    }

    suspend fun suggestPlaylist(tracks: List<JamMediaItem>) {
        if (_role.value != JamRole.Guest) return
        sendMessage(JamMessage.SuggestPlaylist(tracks))
    }

    // ---------- Host moderation ----------

    suspend fun kickParticipant(participantId: String, reason: String = "kicked by host") {
        if (_role.value != JamRole.Host) return
        log.i { "Kicking participant $participantId" }
        sendMessage(JamMessage.Kick(participantId, reason), guestId = participantId)
        removeGuest(participantId)
    }

    suspend fun banParticipant(participantId: String) {
        if (_role.value != JamRole.Host) return
        val deviceId = guestDeviceIds[participantId]
        if (deviceId != null) {
            bannedDeviceIds += deviceId
            log.i { "Banning device $deviceId (participant $participantId)" }
        }
        kickParticipant(participantId, "banned by host")
    }

    private suspend fun removeGuest(guestId: String) {
        val pc = connectedGuests.remove(guestId)
        runCatching { pc?.shutdown() }
        guestDeviceIds.remove(guestId)
        guestConnectionStates.remove(guestId)
        _participants.update { current ->
            current.filterNot { it.id == guestId }
        }
        broadcastParticipantList()
    }

    private suspend fun broadcastParticipantList() {
        if (_role.value != JamRole.Host) return
        sendMessage(JamMessage.ParticipantList(_participants.value))
    }

    /**
     * ICE servers for global peer-to-peer jam sessions: multiple STUN servers for
     * NAT traversal plus a TURN relay for symmetric NATs and strict firewalls.
     */
    private fun defaultIceServers(): List<IceServerConfig> = listOf(
        IceServerConfig(
            urls = listOf(
                "stun:stun.cloudflare.com:3478",
                "stun:stun1.l.google.com:19302",
                "stun:stun.l.google.com:19302",
            ),
            username = "",
            credential = "",
        ),
        IceServerConfig(
            urls = listOf("turn:openrelay.metered.ca:80"),
            username = "openrelayproject",
            credential = "openrelayproject",
        ),
    )

    private suspend fun resolveParticipantName(defaultPrefix: String): String {
        val settings = settingsProvider.settingsState.first()
        return settings?.jamParticipantName?.ifBlank { "$defaultPrefix-${randomShortId()}" }
            ?: "$defaultPrefix-${randomShortId()}"
    }

    private fun localDeviceId(): String {
        return settingsProvider.settingsState.value?.remoteControlDeviceId
            ?: "device-${randomShortId()}"
    }

    /**
     * Per-guest handler so messages received on a guest's connection can be
     * attributed back to that guest (needed for kick-on-leave and targeted sends).
     */
    private fun guestEventHandler(guestId: String) = object : WebrtcEventHandler {
        override fun onIceCandidate(candidate: String) {
            log.i { "[$guestId] ICE candidate: $candidate" }
        }

        override fun onIceGatheringStateChange(state: String) {
            log.i { "[$guestId] ICE gathering state: $state" }
        }

        override fun onConnectionStateChange(state: String) {
            log.i { "[$guestId] Connection state: $state" }
            guestConnectionStates[guestId] = state
            if (state == "failed" || state == "closed") {
                scope.launch { removeGuest(guestId) }
            }
        }

        override fun onDataChannelOpen(label: String) {
            log.i { "[$guestId] Data channel '$label' open" }
            _isConnected.value = true
        }

        override fun onDataChannelMessage(label: String, data: String) {
            handleIncomingMessage(data, fromGuestId = guestId)
        }

        override fun onDataChannelClose(label: String) {
            log.i { "[$guestId] Data channel closed" }
            if (_role.value == JamRole.Host) {
                scope.launch { removeGuest(guestId) }
            }
        }
    }

    private val eventHandler = object : WebrtcEventHandler {
        override fun onIceCandidate(candidate: String) {
            log.i { "ICE candidate: $candidate" }
        }

        override fun onIceGatheringStateChange(state: String) {
            log.i { "ICE gathering state: $state" }
        }

        override fun onConnectionStateChange(state: String) {
            log.i { "Connection state: $state" }
            if (state == "failed" || state == "closed") {
                scope.launch { leave() }
            }
        }

        override fun onDataChannelOpen(label: String) {
            log.i { "Data channel '$label' open" }
            _isConnected.value = true
            // Introduce ourselves so the host can fill in our name and hand us
            // our participant id.
            scope.launch {
                sendMessage(JamMessage.Hello(guestDisplayName, localDeviceId()))
            }
        }

        override fun onDataChannelMessage(label: String, data: String) {
            handleIncomingMessage(data, fromGuestId = null)
        }

        override fun onDataChannelClose(label: String) {
            log.i { "Data channel closed" }
            scope.launch { leave() }
        }
    }

    private fun handleIncomingMessage(data: String, fromGuestId: String?) {
        try {
            val message = json.decodeFromString(JamMessage.serializer(), data)
            _incomingMessages.tryEmit(message)
            when (message) {
                is JamMessage.SuggestTrack, is JamMessage.SuggestPlaylist -> {
                    _incomingSuggestions.tryEmit(message)
                }

                is JamMessage.Hello -> {
                    if (_role.value == JamRole.Host && fromGuestId != null) {
                        handleHello(fromGuestId, message)
                    }
                }

                is JamMessage.Welcome -> {
                    if (_role.value == JamRole.Guest) {
                        _localParticipantId.value = message.participantId
                        _participants.update { current ->
                            current.map { participant ->
                                if (participant.isHost) {
                                    participant.copy(displayName = message.hostName.ifBlank { participant.displayName })
                                } else {
                                    participant
                                }
                            }
                        }
                        log.i { "Welcome: joined as ${message.participantId}" }
                    }
                }

                is JamMessage.ParticipantList -> {
                    if (_role.value == JamRole.Guest) {
                        _participants.value = message.participants
                    }
                }

                is JamMessage.Kick -> {
                    if (_role.value == JamRole.Guest) {
                        log.i { "Kicked by host: ${message.reason}" }
                        scope.launch { leave() }
                    }
                }

                is JamMessage.Leave -> {
                    if (_role.value == JamRole.Host && fromGuestId != null) {
                        scope.launch { removeGuest(fromGuestId) }
                    } else if (_role.value == JamRole.Guest) {
                        scope.launch { leave() }
                    }
                }

                else -> Unit
            }
        } catch (e: Exception) {
            log.w(e) { "Failed to parse jam message" }
        }
    }

    private fun handleHello(guestId: String, hello: JamMessage.Hello) {
        val deviceId = hello.deviceId
        if (deviceId in bannedDeviceIds) {
            log.w { "Rejecting banned device $deviceId" }
            scope.launch {
                sendMessage(
                    JamMessage.Kick(guestId, "banned by host"),
                    guestId = guestId,
                )
                removeGuest(guestId)
            }
            return
        }
        guestDeviceIds[guestId] = deviceId
        _participants.update { current ->
            current.map { participant ->
                if (participant.id == guestId) {
                    participant.copy(displayName = hello.displayName.ifBlank { participant.displayName })
                } else {
                    participant
                }
            }
        }
        scope.launch {
            sendMessage(
                JamMessage.Welcome(hostDisplayName, guestId),
                guestId = guestId,
            )
            broadcastParticipantList()
            // Give the newly joined guest the current queue + playback state.
            queueSyncManager.broadcastNow()
        }
    }

    private suspend fun shutdownAll() {
        pendingInvites.values.forEach { runCatching { it.shutdown() } }
        connectedGuests.values.forEach { runCatching { it.shutdown() } }
        runCatching { hostConnection?.shutdown() }
        pendingInvites.clear()
        connectedGuests.clear()
        hostConnection = null
    }
}

private const val CHANNEL_LABEL = "jam"

private fun <T> MutableStateFlow<T>.update(transform: (T) -> T) {
    value = transform(value)
}

private fun randomShortId(): String {
    val chars = "0123456789abcdef"
    return buildString(8) {
        repeat(8) {
            append(chars[kotlin.random.Random.nextInt(chars.length)])
        }
    }
}