final spotifyMarkets = [
  "Andorra (AD)",
  "United Arab Emirates (AE)",
  "Antigua and Barbuda (AG)",
  "Albania (AL)",
  "Armenia (AM)",
  "Angola (AO)",
  "Argentina (AR)",
  "Austria (AT)",
  "Australia (AU)",
  "Azerbaijan (AZ)",
  "Bosnia and Herzegovina  (BA)",
  "Barbados (BB)",
  "Bangladesh (BD)",
  "Belgium (BE)",
  "Burkina Faso (BF)",
  "Bulgaria (BG)",
  "Bahrain (BH)",
  "Burundi (BI)",
  "Benin (BJ)",
  "Brunei Darussalam (BN)",
  "Bolivia (BO)",
  "Brazil (BR)",
  "The Bahamas (BS)",
  "Bhutan (BT)",
  "Botswana (BW)",
  "Belarus (BY)",
  "Belize (BZ)",
  "Canada (CA)",
  "Democratic Republic of the Congo (CD)",
  "Republic of the Congo (CG)",
  "Switzerland (CH)",
  "Côte d'Ivoire / Ivory Coast  (CI)",
  "Chile (CL)",
  "Cameroon (CM)",
  "Colombia (CO)",
  "Costa Rica (CR)",
  "Cabo Verde / Cape Verde (CV)",
  "Curaçao (CW)",
  "Cyprus (CY)",
  "Czech Republic (CZ)",
  "Germany (DE)",
  "Djibouti (DJ)",
  "Denmark (DK)",
  "Dominica (DM)",
  "Dominican Republic (DO)",
  "Algeria (DZ)",
  "Ecuador (EC)",
  "Estonia (EE)",
  "Egypt (EG)",
  "Spain (ES)",
  "Finland (FI)",
  "Fiji (FJ)",
  "Micronesia (FM)",
  "France (FR)",
  "Gabon (GA)",
  "United Kingdom (GB)",
  "Grenada (GD)",
  "Georgia (GE)",
  "Ghana (GH)",
  "The Gambia (GM)",
  "Guinea (GN)",
  "Equatorial Guinea (GQ)",
  "Greece (GR)",
  "Guatemala (GT)",
  "Guinea-Bissau (GW)",
  "Guyana (GY)",
  "Hong Kong (HK)",
  "Honduras (HN)",
  "Croatia (HR)",
  "Haiti (HT)",
  "Hungary (HU)",
  "Indonesia (ID)",
  "Ireland (IE)",
  "Israel (IL)",
  "India (IN)",
  "Iraq (IQ)",
  "Iceland (IS)",
  "Italy (IT)",
  "Jamaica (JM)",
  "Jordan (JO)",
  "Japan (JP)",
  "Kenya (KE)",
  "Kyrgyzstan (KG)",
  "Cambodia (KH)",
  "Kiribati (KI)",
  "Comoros (KM)",
  "St. Kitts and Nevis (KN)",
  "South Korea (KR)",
  "Kuwait (KW)",
  "Kazakhstan (KZ)",
  "Laos (LA)",
  "Lebanon (LB)",
  "St. Lucia (LC)",
  "Liechtenstein (LI)",
  "Sri Lanka (LK)",
  "Liberia (LR)",
  "Lesotho (LS)",
  "Lithuania (LT)",
  "Luxembourg (LU)",
  "Latvia (LV)",
  "Libya (LY)",
  "Morocco (MA)",
  "Monaco (MC)",
  "Moldova (MD)",
  "Montenegro (ME)",
  "Madagascar (MG)",
  "Marshall Islands (MH)",
  "North Macedonia (MK)",
  "Mali (ML)",
  "Mongolia (MN)",
  "Macao / Macau (MO)",
  "Mauritania (MR)",
  "Malta (MT)",
  "Mauritius (MU)",
  "Maldives (MV)",
  "Malawi (MW)",
  "Mexico (MX)",
  "Malaysia (MY)",
  "Mozambique (MZ)",
  "Namibia (NA)",
  "Niger (NE)",
  "Nigeria (NG)",
  "Nicaragua (NI)",
  "Netherlands (NL)",
  "Norway (NO)",
  "Nepal (NP)",
  "Nauru (NR)",
  "New Zealand (NZ)",
  "Oman (OM)",
  "Panama (PA)",
  "Peru (PE)",
  "Papua New Guinea (PG)",
  "Philippines (PH)",
  "Pakistan (PK)",
  "Poland (PL)",
  "Palestine (PS)",
  "Portugal (PT)",
  "Palau (PW)",
  "Paraguay (PY)",
  "Qatar (QA)",
  "Romania (RO)",
  "Serbia (RS)",
  "Russia (RU)",
  "Rwanda (RW)",
  "Saudi Arabia (SA)",
  "Solomon Islands (SB)",
  "Seychelles (SC)",
  "Sweden (SE)",
  "Singapore (SG)",
  "Slovenia (SI)",
  "Slovakia (SK)",
  "Sierra Leone (SL)",
  "San Marino (SM)",
  "Senegal (SN)",
  "Suriname (SR)",
  "São Tomé and Príncipe (ST)",
  "El Salvador (SV)",
  "Eswatini (SZ)",
  "Chad (TD)",
  "Togo (TG)",
  "Thailand (TH)",
  "Tajikistan (TJ)",
  "Timor-Leste / East Timor (TL)",
  "Tunisia (TN)",
  "Tonga (TO)",
  "Turkey (TR)",
  "Trinidad and Tobago (TT)",
  "Tuvalu (TV)",
  "Taiwan (TW)",
  "Tanzania (TZ)",
  "Ukraine (UA)",
  "Uganda (UG)",
  "United States (US)",
  "Uruguay (UY)",
  "Uzbekistan (UZ)",
  "St Vincent and the Grenadines (VC)",
  "Venezuela (VE)",
  "Vietnam (VN)",
  "Vanuatu (VU)",
  "Samoa (WS)",
  "Kosovo (XK)",
  "South Africa (ZA)",
  "Zambia (ZM)",
  "Zimbabwe (ZW)"
];
