// Country Codes contributed by momobobe <https://github.com/momobobe>

import 'package:spotube/models/metadata/market.dart';

final marketsMap = [
  (Market.AL, "Albania (AL)"),
  (Market.DZ, "Algeria (DZ)"),
  (Market.AD, "Andorra (AD)"),
  (Market.AO, "Angola (AO)"),
  (Market.AG, "Antigua and Barbuda (AG)"),
  (Market.AR, "Argentina (AR)"),
  (Market.AM, "Armenia (AM)"),
  (Market.AU, "Australia (AU)"),
  (Market.AT, "Austria (AT)"),
  (Market.AZ, "Azerbaijan (AZ)"),
  (Market.BH, "Bahrain (BH)"),
  (Market.BD, "Bangladesh (BD)"),
  (Market.BB, "Barbados (BB)"),
  (Market.BY, "Belarus (BY)"),
  (Market.BE, "Belgium (BE)"),
  (Market.BZ, "Belize (BZ)"),
  (Market.BJ, "Benin (BJ)"),
  (Market.BT, "Bhutan (BT)"),
  (Market.BO, "Bolivia (BO)"),
  (Market.BA, "Bosnia and Herzegovina (BA)"),
  (Market.BW, "Botswana (BW)"),
  (Market.BR, "Brazil (BR)"),
  (Market.BN, "Brunei Darussalam (BN)"),
  (Market.BG, "Bulgaria (BG)"),
  (Market.BF, "Burkina Faso (BF)"),
  (Market.BI, "Burundi (BI)"),
  (Market.CV, "Cabo Verde / Cape Verde (CV)"),
  (Market.KH, "Cambodia (KH)"),
  (Market.CM, "Cameroon (CM)"),
  (Market.CA, "Canada (CA)"),
  (Market.TD, "Chad (TD)"),
  (Market.CL, "Chile (CL)"),
  (Market.CO, "Colombia (CO)"),
  (Market.KM, "Comoros (KM)"),
  (Market.CR, "Costa Rica (CR)"),
  (Market.HR, "Croatia (HR)"),
  (Market.CW, "Curaçao (CW)"),
  (Market.CY, "Cyprus (CY)"),
  (Market.CZ, "Czech Republic (CZ)"),
  (Market.CI, "Ivory Coast (CI)"),
  (Market.CD, "Congo (CD)"),
  (Market.DK, "Denmark (DK)"),
  (Market.DJ, "Djibouti (DJ)"),
  (Market.DM, "Dominica (DM)"),
  (Market.DO, "Dominican Republic (DO)"),
  (Market.EC, "Ecuador (EC)"),
  (Market.EG, "Egypt (EG)"),
  (Market.SV, "El Salvador (SV)"),
  (Market.GQ, "Equatorial Guinea (GQ)"),
  (Market.EE, "Estonia (EE)"),
  (Market.SZ, "Eswatini (SZ)"),
  (Market.FJ, "Fiji (FJ)"),
  (Market.FI, "Finland (FI)"),
  (Market.FR, "France (FR)"),
  (Market.GA, "Gabon (GA)"),
  (Market.GE, "Georgia (GE)"),
  (Market.DE, "Germany (DE)"),
  (Market.GH, "Ghana (GH)"),
  (Market.GR, "Greece (GR)"),
  (Market.GD, "Grenada (GD)"),
  (Market.GT, "Guatemala (GT)"),
  (Market.GN, "Guinea (GN)"),
  (Market.GW, "Guinea-Bissau (GW)"),
  (Market.GY, "Guyana (GY)"),
  (Market.HT, "Haiti (HT)"),
  (Market.HN, "Honduras (HN)"),
  (Market.HK, "Hong Kong (HK)"),
  (Market.HU, "Hungary (HU)"),
  (Market.IS, "Iceland (IS)"),
  (Market.IN, "India (IN)"),
  (Market.ID, "Indonesia (ID)"),
  (Market.IQ, "Iraq (IQ)"),
  (Market.IE, "Ireland (IE)"),
  (Market.IL, "Israel (IL)"),
  (Market.IT, "Italy (IT)"),
  (Market.JM, "Jamaica (JM)"),
  (Market.JP, "Japan (JP)"),
  (Market.JO, "Jordan (JO)"),
  (Market.KZ, "Kazakhstan (KZ)"),
  (Market.KE, "Kenya (KE)"),
  (Market.KI, "Kiribati (KI)"),
  (Market.XK, "Kosovo (XK)"),
  (Market.KW, "Kuwait (KW)"),
  (Market.KG, "Kyrgyzstan (KG)"),
  (Market.LA, "Laos (LA)"),
  (Market.LV, "Latvia (LV)"),
  (Market.LB, "Lebanon (LB)"),
  (Market.LS, "Lesotho (LS)"),
  (Market.LR, "Liberia (LR)"),
  (Market.LY, "Libya (LY)"),
  (Market.LI, "Liechtenstein (LI)"),
  (Market.LT, "Lithuania (LT)"),
  (Market.LU, "Luxembourg (LU)"),
  (Market.MO, "Macao / Macau (MO)"),
  (Market.MG, "Madagascar (MG)"),
  (Market.MW, "Malawi (MW)"),
  (Market.MY, "Malaysia (MY)"),
  (Market.MV, "Maldives (MV)"),
  (Market.ML, "Mali (ML)"),
  (Market.MT, "Malta (MT)"),
  (Market.MH, "Marshall Islands (MH)"),
  (Market.MR, "Mauritania (MR)"),
  (Market.MU, "Mauritius (MU)"),
  (Market.MX, "Mexico (MX)"),
  (Market.FM, "Micronesia (FM)"),
  (Market.MD, "Moldova (MD)"),
  (Market.MC, "Monaco (MC)"),
  (Market.MN, "Mongolia (MN)"),
  (Market.ME, "Montenegro (ME)"),
  (Market.MA, "Morocco (MA)"),
  (Market.MZ, "Mozambique (MZ)"),
  (Market.NA, "Namibia (NA)"),
  (Market.NR, "Nauru (NR)"),
  (Market.NP, "Nepal (NP)"),
  (Market.NL, "Netherlands (NL)"),
  (Market.NZ, "New Zealand (NZ)"),
  (Market.NI, "Nicaragua (NI)"),
  (Market.NE, "Niger (NE)"),
  (Market.NG, "Nigeria (NG)"),
  (Market.MK, "North Macedonia (MK)"),
  (Market.NO, "Norway (NO)"),
  (Market.OM, "Oman (OM)"),
  (Market.PK, "Pakistan (PK)"),
  (Market.PW, "Palau (PW)"),
  (Market.PS, "Palestine (PS)"),
  (Market.PA, "Panama (PA)"),
  (Market.PG, "Papua New Guinea (PG)"),
  (Market.PY, "Paraguay (PY)"),
  (Market.PE, "Peru (PE)"),
  (Market.PH, "Philippines (PH)"),
  (Market.PL, "Poland (PL)"),
  (Market.PT, "Portugal (PT)"),
  (Market.QA, "Qatar (QA)"),
  (Market.CG, "Congo (CG)"),
  (Market.RO, "Romania (RO)"),
  (Market.RU, "Russia (RU)"),
  (Market.RW, "Rwanda (RW)"),
  (Market.WS, "Samoa (WS)"),
  (Market.SM, "San Marino (SM)"),
  (Market.SA, "Saudi Arabia (SA)"),
  (Market.SN, "Senegal (SN)"),
  (Market.RS, "Serbia (RS)"),
  (Market.SC, "Seychelles (SC)"),
  (Market.SL, "Sierra Leone (SL)"),
  (Market.SG, "Singapore (SG)"),
  (Market.SK, "Slovakia (SK)"),
  (Market.SI, "Slovenia (SI)"),
  (Market.SB, "Solomon Islands (SB)"),
  (Market.ZA, "South Africa (ZA)"),
  (Market.KR, "South Korea (KR)"),
  (Market.ES, "Spain (ES)"),
  (Market.LK, "Sri Lanka (LK)"),
  (Market.KN, "St. Kitts and Nevis (KN)"),
  (Market.LC, "St. Lucia (LC)"),
  (Market.SR, "Suriname (SR)"),
  (Market.SE, "Sweden (SE)"),
  (Market.CH, "Switzerland (CH)"),
  (Market.ST, "São Tomé and Príncipe (ST)"),
  (Market.TW, "Taiwan (TW)"),
  (Market.TJ, "Tajikistan (TJ)"),
  (Market.TZ, "Tanzania (TZ)"),
  (Market.TH, "Thailand (TH)"),
  (Market.BS, "The Bahamas (BS)"),
  (Market.GM, "The Gambia (GM)"),
  (Market.TL, "East Timor (TL)"),
  (Market.TG, "Togo (TG)"),
  (Market.TO, "Tonga (TO)"),
  (Market.TT, "Trinidad and Tobago (TT)"),
  (Market.TN, "Tunisia (TN)"),
  (Market.TR, "Turkey (TR)"),
  (Market.TV, "Tuvalu (TV)"),
  (Market.UG, "Uganda (UG)"),
  (Market.UA, "Ukraine (UA)"),
  (Market.AE, "United Arab Emirates (AE)"),
  (Market.GB, "United Kingdom (GB)"),
  (Market.US, "United States (US)"),
  (Market.UY, "Uruguay (UY)"),
  (Market.UZ, "Uzbekistan (UZ)"),
  (Market.VU, "Vanuatu (VU)"),
  (Market.VE, "Venezuela (VE)"),
  (Market.VN, "Vietnam (VN)"),
  (Market.ZM, "Zambia (ZM)"),
  (Market.ZW, "Zimbabwe (ZW)"),
];
