import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter_feather_icons/flutter_feather_icons.dart';

abstract class SpotubeIcons {
  static const home = FluentIcons.home;
  static const search = FeatherIcons.search;
  static const library = FluentIcons.library;
  static const music = FeatherIcons.music;
  static const play = FluentIcons.play;
  static const pause = FeatherIcons.pause;
  static const skipForward = FeatherIcons.skipForward;
  static const skipBack = FeatherIcons.skipBack;
  static const stop = FeatherIcons.square;
  static const filter = FeatherIcons.filter;
  static const refresh = FeatherIcons.refreshCw;
  static const settings = FeatherIcons.settings;
  static const shuffle = FeatherIcons.shuffle;
  static const repeat = FluentIcons.repeat_all;
  static const repeatOne = FluentIcons.repeat_one;
  static const remove = FeatherIcons.minus;
  static const removeFilled = FeatherIcons.minusCircle;
  static const add = FeatherIcons.plus;
  static const addFilled = FeatherIcons.plusSquare;
  static const heart = FeatherIcons.heart;
  static const heartFilled = Icons.favorite_rounded;
  static const queue = Icons.queue_music_rounded;
  static const download = FeatherIcons.download;
  static const done = FeatherIcons.checkCircle;
  static const alternativeRoute = Icons.alt_route_rounded;
  static const sort = Icons.sort_rounded;
  static const moreVertical = FeatherIcons.moreVertical;
  static const moreHorizontal = FeatherIcons.moreHorizontal;
  static const share = FeatherIcons.share2;
  static const playlistAdd = Icons.playlist_add_rounded;
  static const playlistRemove = Icons.playlist_remove_rounded;
  static const trash = FeatherIcons.trash2;
  static const clock = FeatherIcons.clock;
  static const lyrics = Icons.lyrics_rounded;
  static const logout = FeatherIcons.logOut;
  static const login = FeatherIcons.logIn;
  static const dashboard = FeatherIcons.grid;
  static const darkMode = FeatherIcons.moon;
  static const platform = FeatherIcons.smartphone;
  static const palette = Icons.palette_outlined;
  static const colorBucket = Icons.format_color_fill_rounded;
  static const album = FeatherIcons.disc;
  static const artist = FeatherIcons.user;
  static const audioQuality = Icons.multitrack_audio_rounded;
  static const fastForward = FeatherIcons.fastForward;
  static const angleRight = FeatherIcons.chevronRight;
  static const angleLeft = FeatherIcons.chevronLeft;
  static const shoppingBag = FeatherIcons.shoppingBag;
  static const screenSearch = Icons.screen_search_desktop_outlined;
  static const save = FeatherIcons.save;
  static const barChart = FeatherIcons.barChart2;
  static const folder = FeatherIcons.folder;
  static const update = FeatherIcons.refreshCcw;
  static const info = FeatherIcons.info;
  static const userRemove = FeatherIcons.userX;
}
