// Country Codes contributed by momobobe <https://github.com/momobobe>

final spotifyMarkets = [
  ("AL", "Albania (AL)"),
  ("DZ", "Algeria (DZ)"),
  ("AD", "Andorra (AD)"),
  ("AO", "Angola (AO)"),
  ("AG", "Antigua and Barbuda (AG)"),
  ("AR", "Argentina (AR)"),
  ("AM", "Armenia (AM)"),
  ("AU", "Australia (AU)"),
  ("AT", "Austria (AT)"),
  ("AZ", "Azerbaijan (AZ)"),
  ("BH", "Bahrain (BH)"),
  ("BD", "Bangladesh (BD)"),
  ("BB", "Barbados (BB)"),
  ("BY", "Belarus (BY)"),
  ("BE", "Belgium (BE)"),
  ("BZ", "Belize (BZ)"),
  ("BJ", "Benin (BJ)"),
  ("BT", "Bhutan (BT)"),
  ("BO", "Bolivia (BO)"),
  ("BA", "Bosnia and Herzegovina (BA)"),
  ("BW", "Botswana (BW)"),
  ("BR", "Brazil (BR)"),
  ("BN", "Brunei Darussalam (BN)"),
  ("BG", "Bulgaria (BG)"),
  ("BF", "Burkina Faso (BF)"),
  ("BI", "Burundi (BI)"),
  ("CV", "Cabo Verde / Cape Verde (CV)"),
  ("KH", "Cambodia (KH)"),
  ("CM", "Cameroon (CM)"),
  ("CA", "Canada (CA)"),
  ("TD", "Chad (TD)"),
  ("CL", "Chile (CL)"),
  ("CO", "Colombia (CO)"),
  ("KM", "Comoros (KM)"),
  ("CR", "Costa Rica (CR)"),
  ("HR", "Croatia (HR)"),
  ("CW", "Curaçao (CW)"),
  ("CY", "Cyprus (CY)"),
  ("CZ", "Czech Republic (CZ)"),
  ("CI", "Ivory Coast (CI)"),
  ("CD", "Congo (CD)"),
  ("DK", "Denmark (DK)"),
  ("DJ", "Djibouti (DJ)"),
  ("DM", "Dominica (DM)"),
  ("DO", "Dominican Republic (DO)"),
  ("EC", "Ecuador (EC)"),
  ("EG", "Egypt (EG)"),
  ("SV", "El Salvador (SV)"),
  ("GQ", "Equatorial Guinea (GQ)"),
  ("EE", "Estonia (EE)"),
  ("SZ", "Eswatini (SZ)"),
  ("FJ", "Fiji (FJ)"),
  ("FI", "Finland (FI)"),
  ("FR", "France (FR)"),
  ("GA", "Gabon (GA)"),
  ("GE", "Georgia (GE)"),
  ("DE", "Germany (DE)"),
  ("GH", "Ghana (GH)"),
  ("GR", "Greece (GR)"),
  ("GD", "Grenada (GD)"),
  ("GT", "Guatemala (GT)"),
  ("GN", "Guinea (GN)"),
  ("GW", "Guinea-Bissau (GW)"),
  ("GY", "Guyana (GY)"),
  ("HT", "Haiti (HT)"),
  ("HN", "Honduras (HN)"),
  ("HK", "Hong Kong (HK)"),
  ("HU", "Hungary (HU)"),
  ("IS", "Iceland (IS)"),
  ("IN", "India (IN)"),
  ("ID", "Indonesia (ID)"),
  ("IQ", "Iraq (IQ)"),
  ("IE", "Ireland (IE)"),
  ("IL", "Israel (IL)"),
  ("IT", "Italy (IT)"),
  ("JM", "Jamaica (JM)"),
  ("JP", "Japan (JP)"),
  ("JO", "Jordan (JO)"),
  ("KZ", "Kazakhstan (KZ)"),
  ("KE", "Kenya (KE)"),
  ("KI", "Kiribati (KI)"),
  ("XK", "Kosovo (XK)"),
  ("KW", "Kuwait (KW)"),
  ("KG", "Kyrgyzstan (KG)"),
  ("LA", "Laos (LA)"),
  ("LV", "Latvia (LV)"),
  ("LB", "Lebanon (LB)"),
  ("LS", "Lesotho (LS)"),
  ("LR", "Liberia (LR)"),
  ("LY", "Libya (LY)"),
  ("LI", "Liechtenstein (LI)"),
  ("LT", "Lithuania (LT)"),
  ("LU", "Luxembourg (LU)"),
  ("MO", "Macao / Macau (MO)"),
  ("MG", "Madagascar (MG)"),
  ("MW", "Malawi (MW)"),
  ("MY", "Malaysia (MY)"),
  ("MV", "Maldives (MV)"),
  ("ML", "Mali (ML)"),
  ("MT", "Malta (MT)"),
  ("MH", "Marshall Islands (MH)"),
  ("MR", "Mauritania (MR)"),
  ("MU", "Mauritius (MU)"),
  ("MX", "Mexico (MX)"),
  ("FM", "Micronesia (FM)"),
  ("MD", "Moldova (MD)"),
  ("MC", "Monaco (MC)"),
  ("MN", "Mongolia (MN)"),
  ("ME", "Montenegro (ME)"),
  ("MA", "Morocco (MA)"),
  ("MZ", "Mozambique (MZ)"),
  ("NA", "Namibia (NA)"),
  ("NR", "Nauru (NR)"),
  ("NP", "Nepal (NP)"),
  ("NL", "Netherlands (NL)"),
  ("NZ", "New Zealand (NZ)"),
  ("NI", "Nicaragua (NI)"),
  ("NE", "Niger (NE)"),
  ("NG", "Nigeria (NG)"),
  ("MK", "North Macedonia (MK)"),
  ("NO", "Norway (NO)"),
  ("OM", "Oman (OM)"),
  ("PK", "Pakistan (PK)"),
  ("PW", "Palau (PW)"),
  ("PS", "Palestine (PS)"),
  ("PA", "Panama (PA)"),
  ("PG", "Papua New Guinea (PG)"),
  ("PY", "Paraguay (PY)"),
  ("PE", "Peru (PE)"),
  ("PH", "Philippines (PH)"),
  ("PL", "Poland (PL)"),
  ("PT", "Portugal (PT)"),
  ("QA", "Qatar (QA)"),
  ("CG", "Congo (CG)"),
  ("RO", "Romania (RO)"),
  ("RU", "Russia (RU)"),
  ("RW", "Rwanda (RW)"),
  ("WS", "Samoa (WS)"),
  ("SM", "San Marino (SM)"),
  ("SA", "Saudi Arabia (SA)"),
  ("SN", "Senegal (SN)"),
  ("RS", "Serbia (RS)"),
  ("SC", "Seychelles (SC)"),
  ("SL", "Sierra Leone (SL)"),
  ("SG", "Singapore (SG)"),
  ("SK", "Slovakia (SK)"),
  ("SI", "Slovenia (SI)"),
  ("SB", "Solomon Islands (SB)"),
  ("ZA", "South Africa (ZA)"),
  ("KR", "South Korea (KR)"),
  ("ES", "Spain (ES)"),
  ("LK", "Sri Lanka (LK)"),
  ("KN", "St. Kitts and Nevis (KN)"),
  ("LC", "St. Lucia (LC)"),
  ("SR", "Suriname (SR)"),
  ("SE", "Sweden (SE)"),
  ("CH", "Switzerland (CH)"),
  ("ST", "São Tomé and Príncipe (ST)"),
  ("TW", "Taiwan (TW)"),
  ("TJ", "Tajikistan (TJ)"),
  ("TZ", "Tanzania (TZ)"),
  ("TH", "Thailand (TH)"),
  ("BS", "The Bahamas (BS)"),
  ("GM", "The Gambia (GM)"),
  ("TL", "East Timor (TL)"),
  ("TG", "Togo (TG)"),
  ("TO", "Tonga (TO)"),
  ("TT", "Trinidad and Tobago (TT)"),
  ("TN", "Tunisia (TN)"),
  ("TR", "Turkey (TR)"),
  ("TV", "Tuvalu (TV)"),
  ("UG", "Uganda (UG)"),
  ("UA", "Ukraine (UA)"),
  ("AE", "United Arab Emirates (AE)"),
  ("GB", "United Kingdom (GB)"),
  ("US", "United States (US)"),
  ("UY", "Uruguay (UY)"),
  ("UZ", "Uzbekistan (UZ)"),
  ("VU", "Vanuatu (VU)"),
  ("VE", "Venezuela (VE)"),
  ("VN", "Vietnam (VN)"),
  ("ZM", "Zambia (ZM)"),
  ("ZW", "Zimbabwe (ZW)"),
];
